services:
  - type: web
    name: 323drop-backend
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
    mounts:
      - name: daily-picks-volume
        path: /var/data
    disk:
      name: user-data
      mountPath: /data
      sizeGB: 1

  - type: cron
    name: daily-pick-generator
    env: node
    plan: free
    schedule: "0 0 * * *"
    buildCommand: "npm install"
    startCommand: "node generateDailyPick.js"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
    mounts:
      - name: daily-picks-volume
        path: /var/data

volumes:
  - name: daily-picks-volume
    sizeGB: 1
