services:
  - type: web
    name: 323drop-backend
    env: node
    plan: free    # or standard depending on your usage
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: OPENAI_API_KEY
        sync: false  # set in Render dashboard
    mounts:
      - name: daily-picks-volume
        path: /var/data

  - type: cron
    name: daily-pick-generator
    env: node
    plan: free
    schedule: "0 0 * * *"   # every midnight UTC
    buildCommand: "npm install"
    startCommand: "node generateDailyPick.js"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
    mounts:
      - name: daily-picks-volume
        path: /var/data

volumes:
  - name: daily-picks-volume
    sizeGB: 1
