/* ----------------------------------------
   323aidrop Ecosystem Topic Pools (50 each)
   ---------------------------------------- */

// Cosmetics — original 50 items
const TOP50_COSMETICS = [
  { brand: "Rhode", product: "Peptide Lip Tint" },
  { brand: "Fenty Beauty", product: "Gloss Bomb Lip Gloss" },
  { brand: "Anastasia Beverly Hills", product: "Clear Brow Gel" },
  { brand: "YSL", product: "Make Me Blush Baby Doll" },
  { brand: "Laura Mercier", product: "Loose Setting Powder" },
  { brand: "Beautyblender", product: "Blending Sponge" },
  { brand: "Givenchy", product: "Prisme Libre Blush" },
  { brand: "Sephora Collection", product: "Pro Brushes" },
  { brand: "COSRX", product: "Advanced Snail 96 Mucin Essence" },
  { brand: "Lush", product: "Dream Cream" },
  { brand: "Nyx", product: "Jumbo Eye Pencil" },
  { brand: "Nars", product: "Radiant Creamy Concealer" },
  { brand: "Too Faced", product: "Better Than Sex Mascara" },
  { brand: "Charlotte Tilbury", product: "Magic Cream" },
  { brand: "Haus Labs", product: "Triclone Foundation" },
  { brand: "Dior", product: "Lip Glow Oil" },
  { brand: "Freck Beauty", product: "Faux Freckle Pen" },
  { brand: "Sol de Janeiro", product: "Brazilian Crush Mist" },
  { brand: "Paula’s Choice", product: "2% BHA Liquid Exfoliant" },
  { brand: "Essence", product: "Lash Princess Mascara" },
  { brand: "Color Wow", product: "Dream Coat Spray" },
  { brand: "Laneige", product: "Lip Sleeping Mask" },
  { brand: "Maybelline", product: "Sky High Mascara" },
  { brand: "Kitsch", product: "Heatless Curl Set" },
  { brand: "Biodance", product: "Bio-Collagen Mask" },
  { brand: "MAC", product: "Squirt Plumping Gloss Stick" },
  { brand: "Clinique", product: "Black Honey Lipstick" },
  { brand: "L’Oréal Paris", product: "Infallible Foundation" },
  { brand: "Isle of Paradise", product: "Self-Tanning Drops" },
  { brand: "Rare Beauty", product: "Liquid Blush" },
  { brand: "SHEGLAM", product: "Makeup Essentials" },
  { brand: "Huda Beauty", product: "Concealer" },
  { brand: "Cécred", product: "Haircare Treatment" },
  { brand: "Medicube", product: "PDRN Pink Glass Glow Set" },
  { brand: "E.L.F.", product: "Halo Glow Powder" },
  { brand: "Bubble Skincare", product: "Gel Cleanser" },
  { brand: "Tower 28 Beauty", product: "SOS Spray" },
  { brand: "Olay", product: "Regenerist Cream" },
  { brand: "I’m From", product: "Rice Toner" },
  { brand: "DIBS Beauty", product: "Desert Island Duo" },
  { brand: "Milk Makeup", product: "Cooling Water Jelly Tint" },
  { brand: "Glow Recipe", product: "Watermelon Dew Drops" },
  { brand: "Danessa Myricks Beauty", product: "Yummy Skin Balm Powder" },
  { brand: "Refy", product: "Brow Sculpt" },
  { brand: "Kosas", product: "Revealer Concealer" },
  { brand: "Bioderma", product: "Micellar Water" },
  { brand: "Embryolisse", product: "Lait-Crème Concentré" },
  { brand: "CurrentBody", product: "LED Hair Growth Helmet" },
  { brand: "Dyson Beauty", product: "Airwrap Styler" }
];

// Music — 50 trending artists + tracks
const TOP_MUSIC = [
  { artist: "Doja Cat", track: "Paint The Town Red" },
  { artist: "Ice Spice", track: "Deli" },
  { artist: "NewJeans", track: "Super Shy" },
  { artist: "Jungkook", track: "Seven" },
  { artist: "The Weeknd", track: "Popular" },
  { artist: "Olivia Rodrigo", track: "Vampire" },
  { artist: "BLACKPINK", track: "Shut Down" },
  { artist: "Drake", track: "IDGAF" },
  { artist: "SZA", track: "Kill Bill" },
  { artist: "Travis Scott", track: "Meltdown" },
  { artist: "Peso Pluma", track: "Ella Baila Sola" },
  { artist: "Karol G", track: "TQG" },
  { artist: "Rema", track: "Calm Down" },
  { artist: "Tyla", track: "Water" },
  { artist: "Billie Eilish", track: "What Was I Made For?" },
  { artist: "Metro Boomin", track: "Creepin'" },
  { artist: "Latto", track: "Lottery" },
  { artist: "Lizzo", track: "About Damn Time" },
  { artist: "Dua Lipa", track: "Dance The Night" },
  { artist: "Miley Cyrus", track: "Flowers" },
  { artist: "Justin Bieber", track: "Honest" },
  { artist: "The Kid LAROI", track: "Stay" },
  { artist: "Taylor Swift", track: "Shake It Off" },
  { artist: "Harry Styles", track: "As It Was" },
  { artist: "Bad Bunny", track: "Tití Me Preguntó" },
  { artist: "Anitta", track: "Envolver" },
  { artist: "Saweetie", track: "Tap In" },
  { artist: "Lil Nas X", track: "Montero" },
  { artist: "Post Malone", track: "Circles" },
  { artist: "Ariana Grande", track: "7 rings" },
  { artist: "Bruno Mars", track: "That's What I Like" },
  { artist: "Lana Del Rey", track: "Summertime Sadness" },
  { artist: "Billie Eilish", track: "Happier Than Ever" },
  { artist: "Post Malone & Swae Lee", track: "Sunflower" },
  { artist: "Beyoncé", track: "Break My Soul" },
  { artist: "ROSALÍA", track: "Despechá" },
  { artist: "Lil Baby", track: "In A Minute" },
  { artist: "Shakira", track: "Bzrp Music Sessions, Vol. 53" },
  { artist: "Ed Sheeran", track: "Bad Habits" },
  { artist: "Kendrick Lamar", track: "N95" },
  { artist: "Megan Thee Stallion", track: "Savage" },
  { artist: "Nicki Minaj", track: "Super Freaky Girl" },
  { artist: "Florence + The Machine", track: "Dog Days Are Over" },
  { artist: "Sam Smith", track: "Unholy" },
  { artist: "Stray Kids", track: "S-Class" },
  { artist: "Seventeen", track: "Super" },
  { artist: "IVE", track: "I AM" },
  { artist: "LE SSERAFIM", track: "Eve, Psyche & the Bluebeard’s wife" },
  { artist: "NCT Dream", track: "Candy" }
];

// Politics — 50 issues + keywords
const TOP_POLITICS = [
  { issue: "Climate Policy", keyword: "Paris Agreement" },
  { issue: "Healthcare", keyword: "Medicare Expansion" },
  { issue: "Education", keyword: "Student Loan Debt" },
  { issue: "Free Speech", keyword: "Social Media Regulation" },
  { issue: "Equality", keyword: "Gender Pay Gap" },
  { issue: "Housing", keyword: "Rent Control" },
  { issue: "Immigration", keyword: "Border Policy" },
  { issue: "Technology", keyword: "AI Regulation" },
  { issue: "Voting Rights", keyword: "Early Voting" },
  { issue: "Environment", keyword: "Plastic Ban" },
  { issue: "Income Inequality", keyword: "Minimum Wage" },
  { issue: "Mental Health", keyword: "Access to Care" },
  { issue: "Reproductive Rights", keyword: "Abortion Access" },
  { issue: "Gun Control", keyword: "Universal Background Checks" },
  { issue: "LGBTQ+ Rights", keyword: "Trans Healthcare" },
  { issue: "Racial Justice", keyword: "Police Reform" },
  { issue: "Water Rights", keyword: "Clean Water Access" },
  { issue: "Food Security", keyword: "Right to Food" },
  { issue: "Disability Rights", keyword: "ADA Enforcement" },
  { issue: "Criminal Justice", keyword: "Prison Reform" },
  { issue: "Homelessness", keyword: "Affordable Shelter" },
  { issue: "Net Neutrality", keyword: "Open Internet" },
  { issue: "Union Rights", keyword: "Right to Organize" },
  { issue: "Privacy", keyword: "Data Protection" },
  { issue: "Renewable Energy", keyword: "Green Jobs" },
  { issue: "Campaign Finance", keyword: "Dark Money" },
  { issue: "Voting Access", keyword: "Mail-In Ballots" },
  { issue: "Indigenous Rights", keyword: "Land Sovereignty" },
  { issue: "Civil Liberties", keyword: "Freedom of Assembly" },
  { issue: "Youth Unemployment", keyword: "Job Creation" },
  { issue: "Tax Justice", keyword: "Progressive Tax" },
  { issue: "Drug Policy", keyword: "Decriminalization" },
  { issue: "Police Accountability", keyword: "Body Cameras" },
  { issue: "Global Migration", keyword: "Refugee Crisis" },
  { issue: "Healthcare Access", keyword: "Telehealth" },
  { issue: "Digital Divide", keyword: "Broadband Access" },
  { issue: "Consumer Privacy", keyword: "Surveillance Reform" },
  { issue: "Corruption", keyword: "Government Transparency" },
  { issue: "Food Waste", keyword: "Sustainability Practices" },
  { issue: "Childcare", keyword: "Universal Pre-K" },
  { issue: "Transportation", keyword: "Public Transit" },
  { issue: "Climate Adaptation", keyword: "Flood Protection" },
  { issue: "AI Ethics", keyword: "Bias in Algorithms" },
  { issue: "Animal Rights", keyword: "Factory Farming" },
  { issue: "Trade", keyword: "Tariffs" },
  { issue: "Foreign Policy", keyword: "Ukraine Aid" },
  { issue: "Labor", keyword: "Gig Worker Rights" }
];

// Aidrop — 50 canon AI-native concepts
const TOP_AIDROP = [
  { concept: "Infinite TikTok Loop" },
  { concept: "AI Noodles" },
  { concept: "Talking to GPT Bestie" },
  { concept: "Meme Economy" },
  { concept: "Glitch Selfies" },
  { concept: "Streamed Ramen Nights" },
  { concept: "Algorithm Crush" },
  { concept: "Digital Graffiti" },
  { concept: "NicheTok Clans" },
  { concept: "Creator Paycheck-to-Drop" },
  { concept: "Virtual Concert Vibes" },
  { concept: "Bot Dance Challenges" },
  { concept: "AI Filter Skin" },
  { concept: "Dreamcore Aesthetic" },
  { concept: "Hacking Your Algorithm" },
  { concept: "Digital Thrift Haul" },
  { concept: "Creator Burnout Loop" },
  { concept: "Clone Selfies" },
  { concept: "Augmented Reality Hangouts" },
  { concept: "Sound-Swipe Culture" },
  { concept: "Fail Meme Montage" },
  { concept: "Infinite Scroll Shame" },
  { concept: "Chatbot Crush" },
  { concept: "Daily Drops Addiction" },
  { concept: "Glitch Text Overlays" },
  { concept: "Remix Obsession" },
  { concept: "TikTok Drip Fits" },
  { concept: "AI-Synth Beats" },
  { concept: "Automated Selfies" },
  { concept: "Filter Bubble Reality" },
  { concept: "NFT Dream" },
  { concept: "Pixelated Memories" },
  { concept: "Cyber Ramen Wars" },
  { concept: "Mosaic Screens" },
  { concept: "Viral Soundboard" },
  { concept: "Emoji Overload" },
  { concept: "Algorithmic Love Stories" },
  { concept: "Feed-Fever Loops" },
  { concept: "Synthwave Nights" },
  { concept: "GlitchBot Diaries" },
  { concept: "AI Cityscape Dreams" },
  { concept: "Underground Soundwave" },
  { concept: "Stream Collapse" },
  { concept: "Pop-Up Culture Rooms" },
  { concept: "Hashtag Graffiti Walls" },
  { concept: "Looped Life Clips" },
  { concept: "AI DJ Sets" },
  { concept: "Selfie Clone Wars" },
  { concept: "Algorithm Mood Swings" },
  { concept: "AI Ramen Cook-Off" }
];

// Export all
module.exports = {
  TOP50_COSMETICS,
  TOP_MUSIC,
  TOP_POLITICS,
  TOP_AIDROP
};
